
        slices:
        - sources:
            - model: mlabonne/grandpythia-200k-70m
              layer_range: [0, 32]
            - model: EleutherAI/pythia-70m-deduped
              layer_range: [0, 32]
        merge_method: slerp
        base_model: mlabonne/grandpythia-200k-70m
        parameters:
          t:
            - value: 0.5
        dtype: bfloat16
        